POST  ticketing.dev/api/Users/signup
Content-Type: application/json

{
  "email": "testuser31@gmail.com",
  "password": "test"
}

###
POST  ticketing.dev/api/Users/signin
Content-Type: application/json

{
  "email": "testuser31@gmail.com",
  "password": "test"
}

###
GET  ticketing.dev/api/Users/currentuser

###
POST  ticketing.dev/api/Users/signout

###
GET ticketing.dev/api/tickets

###
POST ticketing.dev/api/tickets
Content-Type: application/json

{
  "title": "new ticket",
  "price": 100
}

###
GET ticketing.dev/api/tickets/6a51aaf5bab10ee90dc918ca

###
PUT ticketing.dev/api/tickets/6a5c7192b2a869cb2167123a
Content-Type: application/json

{
  "title": "updated ticket",
  "price": 10
}

